### ISSUE TITLE
3er Jury-Team - "Newcomer Award" finden + ein Sprecher benennen

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/awards#3]
Jurymitglieder
- Brigitte Hulliger (bestätigt)
- Urs Stender (bestätigt)
- Nino Müller (bestätigt)

**Comment by fbgiardina** [comment]
- Stefanie Bosshard? (Direktorin DSJ)

**Comment by fbgiardina** [comment]
- Linda Sulzer (M Engagement)
- Nino Müller (Impact Hub Bern)
