### ISSUE TITLE
3er Jury-Team - "Open Government Award" finden + ein Sprecher benennen

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/awards#4]
Jurymitglieder
- [x] Alenka Bonnard (bestätigt)
- [x] Che Wagner
- [x] Andreas von Gunten

**Comment by fbgiardina** [comment]
Frankie fragt an:
- Alenka Bonnard
- Nenad Stojanović
- Dani Graf / Che Wagner
- Judith Bellaiche (war ja letztes Jahr dabei, schon angefragt?)

**Comment by MarkusTiede** [comment]
- Hannes Gassert (angefragt?)
