### ISSUE TITLE
Mozilla Hubs

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/awards#42]
We are looking into some ideas for running part of the DINAcon (HACKnight, Awards, ..) in a virtual environment. Mozilla Hubs is an open source platform which we are evaluating.

## Getting Started with Mozilla Hubs

[![YouTube Video Link](https://img.youtube.com/vi/5QnOsyyebEQ/0.jpg)](https://www.youtube.com/watch?v=5QnOsyyebEQ)

## How to use Hubs' basic features & controls

[![YouTube Video Link](https://img.youtube.com/vi/YppUt2N811k/0.jpg)](https://www.youtube.com/watch?v=YppUt2N811k)

## Presenting in Hubs
[![YouTube Video Link](https://img.youtube.com/vi/vkI-5ALoOC8/0.jpg)](https://www.youtube.com/watch?v=vkI-5ALoOC8)

**Comment by loleg** [comment]
That worked well :-)

See it in action: https://youtu.be/xDKVweM_Alo?t=20033
Sources: https://github.com/DINAcon/awards/tree/master/2020/hubs
HACKnight: https://hacknight.dinacon.ch/project/36
