### ISSUE TITLE
Idea - add category for CMS

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/awards#46]
# why
- https://splashawards.ch -> won't be continued this year
- business use cases up-front -> with impact to upstream OS (funding, contributions, ...)
- solution(s) demonstrations

## ideas
1. add category for CMS
2. add highlight / more weight for business impact / funding in general

### differentiate between 
- upstream open-source projects and 
- downstream (open-core) products & business cases

# references
- https://www.openminds.at

**Comment by pvbergen** [comment]
Currently, we have a conceptual categorization, so a cms can compete with a qms or a custom application.
I am not a fan of creating a category for a certain system type.

We already have space for cms projects, it could be a business project or a government project.
Mabye this is more a discussion of #50

**Comment by MarkusTiede** [comment]
Resolving for now - please feel free to re-open: we agreed on CMS being too specific for now.

**Comment by mirodietiker** [comment]
Yes, discussed. We will check submitting some of the Swiss Drupal SplashAwards showcase projects to the current categories and check with other CMS communities how this all fits.

I see also that the intention would take too much room from DINAcon.
The problem with this approach is that we can not show the project bandwidth and the full impact to emphasize the competitiveness of Open Source CMS against commercial CMSes. We can not use it as a primary source for CMS evaluators as things are too much mixed. To achieve such a goal, it seems we maybe need a separate CMS award / event / ...

I will reevaluate our idea and proposals for the more long term future.
