### ISSUE TITLE
3er Jury-Team - "Business Award" finden + ein Sprecher benennen

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/awards#5]
Jurymitglieder
- [x] Martin Edenhofer (bestätigt)
- [x] Nicola Christener (bestätigt)
- [x] Hannes Gassert (bestätigt)

**Comment by fbgiardina** [comment]
- Nicolas Christener? (statt OK halt einfach Jury Mitglied?)
- Nico Schottelius von ungleich.ch?
- Vallerie Vuillerat (witty works)?
