### ISSUE TITLE
Describe categories and their characteristics 

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/awards#50]

**Comment by pvbergen** [comment]
We have some text on that: https://awards.dinacon.ch/awards-kategorien-2020/
I really like this idea of classifying projects according to result, not technology used.

**Comment by pvbergen** [comment]
We currently limit the awards based on the type of nominee (company, government, etc.). 
E.g.
> Der DINAcon „Business-Award“ sollen Unternehmen und Organisationen ausgezeichnet werden, welche in ihrem Geschäftsmodell offene Standarts integrieren oder durch Umsetzung der digitalen Transformation in einer Weise Nutzen für die Gesellschaft generieren.
or
> Verwaltungen, die Open Source-Software erfolgreich einsetzen, offene Daten bereitstellen oder offene Standards etablieren, können sich für die Kategorie „Open Gouvernment Award“ bewerben. Mit diesem Preis wird der besonders vorbildlichen Umgang mit Open-Themen honoriert.

We could open that up and allow anybody to apply to any category and focus more on the achievement of the project instead of the source.

**Comment by MarkusTiede** [comment]
Proposal available here: https://github.com/DINAcon/awards/pull/52
