### ISSUE TITLE
OK Meeting 18. Mai

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/awards#58]
Follow up to https://github.com/DINAcon/event/issues/9

## teaser ✅
[![YouTube Video Link](https://img.youtube.com/vi/BYzCP--Bv6c/0.jpg)](https://www.youtube.com/watch?v=BYzCP--Bv6c)

**Comment by mariafanger** [comment]
**Awards Traktanden:**
- Joel braucht 8h für das Awards Formular → liegt im Budget?
- Awards Seite deutsch/englisch
- Awards Projekte mit Ausstrahlwert auf die Schweiz, ganz Europa?
- upstream/downstream als 2. Kategorieebene, Vorschlag von Miro
- DN Label für Projekte, Qualitätsmässig über die Jahre verfolgen

**Comment by MarkusTiede** [comment]
Oleg (desktop)
18:05
On now: EU's "gathering of progressive innovators, who make the internet democratic, responsible, and sustainable." #NGIForum21

Ma
Matthias Stürmer
18:09
https://igf.swiss/
