### ISSUE TITLE
Initial communication with potential Jury member

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/awards#9]

**Comment by mariafanger** [comment]
Lieber Herr Kellerhals
Letztes Jahr haben Sie die DINAcon Awards massgeblich mit ihrem Engagement in der Awards-Jury unterstützt, vielen Dank dafür!
Auch in diesem Jahr werden am 23. Oktober an der DINAcon Konferenz wieder Awards in 6 Kategorien verliehen und ich freue mich darüber, neu im DINAcon Team dabei zu sein und die Awards Verleihung zusammen mit Torben zu organisieren.
Es wäre toll, wenn wir auch 2020 auf eine grossartige Jury zählen können - deswegen möchte ich Sie anfragen, ob Sie sich vorstellen können, auch in diesem Jahr bei der Auswahl von Sieger-Projekten für die diesjährigen DINAcon Awards dabei zu sein?
Es hat einige kleine Änderungen in den Kategorien gegeben, dieses Jahr werden Awards in folgenden 6 Bereichen vergeben:
-	Open Data Award
-	Business Award
-	Open Gouvernment Award
-	Best Newcomer Award
-	Community Award
-	Open Education Award
Mehr dazu hier: https://awards.dinacon.ch/awards-kategorien-2020/
Das Bewerbungsverfahren wird 2020 zum ersten Mal in zwei Teile unterteilt: eine Nominationsphase, in welcher Projektmitglieder, oder auch externe Personen, die Projekte in einem kurzen und einfachen Formular (https://awards.dinacon.ch/awards-nomination/) nominieren können, worauf sich dann die Projektleiter selbst dann ab dem 30. Juni mit detailierteren Informationen noch definitiv für die Awards bewerben können. Wir hoffen darauf, das Verfahren so niederschwelliger zu gestalten.
Die Nominationsphase hat schon vor einer Woche gestartet und wir sind natürlich froh darum, wenn möglichst viele tolle Nominationen eingehen - der Websitelink zum Formular und Informationen über die DINAcon Awards dürfen sehr gerne geteilt werden! https://awards.dinacon.ch/awards-2020-bewerben/
Ich freue mich auf Ihre Rückmeldung und auf tolle DINAcon Awards 2020!
Liebe Grüsse,
Maria
